### ISSUE TITLE
Problem compiling with ionic 3

### ISSUE THREAD

**Issue by claudiomoratti** [kadoshms/ionic2-autocomplete#38]
Hi,
I'm trying to compile my app (ionic 3 app), but I have this problem:

`[01:34:15]  ngc started ... 
[01:34:17]  ionic-app-script task: "build" 
[01:34:17]  Error: Unexpected value 'AutoCompleteItemComponent in 
            /Users/claudio/Progetti/xxx/node_modules/ionic2-auto-complete/src/autocompleteitem.component.ts' 
            declared by the module 'AutoCompleteModule in 
            /Users/claudio/Progetti/xxx/node_modules/ionic2-auto-complete/index.ts'. Please add a 
            @Pipe/@Directive/@Component annotation. 
Error: Unexpected value 'AutoCompleteItemComponent in /Users/claudio/Progetti/xxx/node_modules/ionic2-auto-complete/src/autocompleteitem.component.ts' declared by the module 'AutoCompleteModule in /Users/claudio/Progetti/xxx/node_modules/ionic2-auto-complete/index.ts'. Please add a @Pipe/@Directive/@Component annotation.
    at Error (native)
    at syntaxError (/Users/claudio/Progetti/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
    at /Users/claudio/Progetti/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:14552:40
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/claudio/Progetti/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:14534:54)
    at addNgModule (/Users/claudio/Progetti/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:23050:58)
    at /Users/claudio/Progetti/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:23061:14
    at Array.forEach (native)
    at _createNgModules (/Users/claudio/Progetti/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:23060:26)
    at analyzeNgModules (/Users/claudio/Progetti/xxx/node_modules/@angular/compiler/bundles/compiler.umd.js:22935:14)`

with ionic serve it works perfectly, but when I try to compile with ' ionic build android --prod --release ' I receive that error

this is my ionic info:
`Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 4.1.1 
OS: macOS Sierra
Node Version: v5.8.0
Xcode version: Xcode 8.3.2 Build version 8E2002`

thank you in advice

**Comment by kadoshms** [comment]
Thanks, I will look into that ASAP

**Comment by kadoshms** [comment]
Fixed, see #20

**Comment by claudiomoratti** [comment]
ciao Mor,
thank you for this fix, but I'm sorry to inform you that there are other issues with ionic 3.

I made some tests, and I found this situation:
- with @ionic/app-scripts >= 1.3.5 the build with --prod options fails with the following error:

`Error: ./~/ionic2-auto-complete/index.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/claudio/Progetti/XXX-v2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/Users/claudio/Progetti/XXX-v2/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 33:0-55
 @ ./src/app/main.ts`

- with @ionic/app-script < 1.3.5 (and > 1.3.1) the build goes ok, but when I start my app I see a white screen and, inside the logcat, I have this log line:

`D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 42 : Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/claudio/Progetti/XXX-v2/node_modules/ionic2-auto-complete/index.js'
05-15 22:25:05.196  3277  3277 I chromium: [INFO:CONSOLE(42)] "Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/claudio/Progetti/XXX-v2/node_modules/ionic2-auto-complete/index.js'", source: file:///android_asset/www/build/main.js (42)`

I attach you my package.json
[package.json.txt](https://github.com/kadoshms/ionic2-autocomplete/files/1002381/package.json.txt)

This is my updated ionic info:
`$ ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 4.1.1 `


Tell me if you need more informations or if I could help you

thank you

**Comment by kadoshms** [comment]
Thanks for reporting, I hope to take a look at it soon, do you have any ideas anyway?

**Comment by FiXIDeA** [comment]
A similar problem:
ionic cordova run android --prod --release
Running app-scripts build: --prod --address 0.0.0.0 --port 8100 --p 8100 --livereload-port 35729 --r 35729 --iscordovaserve --externalIpRequired --nobrowser

[22:23:23]  build prod started ... 
[22:23:23]  clean started ... 
[22:23:23]  clean finished in 2 ms 
[22:23:23]  copy started ... 
[22:23:23]  ngc started ... 
[22:23:28]  ngc finished in 5.06 s 
[22:23:28]  preprocess started ... 
[22:23:28]  deeplinks started ... 
[22:23:28]  deeplinks finished in 228 ms 
[22:23:28]  optimization started ... 
[22:23:28]  copy finished in 5.49 s 
Error: ./~/ionic2-auto-complete/index.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/home/fixidea/projects/broker/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/home/fixidea/projects/broker/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 30:0-55
 @ ./src/app/main.ts,./~/ionic2-auto-complete/src/autocomplete.component.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/home/fixidea/projects/broker/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/home/fixidea/projects/broker/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/pages/map/map.ngfactory.js 19:0-76
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./~/ionic2-auto-complete/src/autocompleteitem.component.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/home/fixidea/projects/broker/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/home/fixidea/projects/broker/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./~/ionic2-auto-complete/src/autocomplete.component.ngfactory.js 9:0-79
 @ ./src/pages/map/map.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./~/ionic2-auto-complete/src/boldprefix.pipe.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/home/fixidea/projects/broker/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/home/fixidea/projects/broker/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./~/ionic2-auto-complete/src/autocompleteitem.component.ngfactory.js 8:0-68
 @ ./~/ionic2-auto-complete/src/autocomplete.component.ngfactory.js
 @ ./src/pages/map/map.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts

fixidea@zalman:~/projects/broker$ ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by kadoshms** [comment]
@claudiomoratti @FiXIDeA I have a fix! please stay patient a little more :)

**Comment by claudiomoratti** [comment]
great! don't worry, If you need tests feel free to write me

**Comment by kadoshms** [comment]
@claudiomoratti @FiXIDeA 

Would you mind trying this one: `npm install --save ionic2-auto-complete@1.4.0-fix-to-38` I haven't commited yet because I want to know if I'm on the right path.
I tested on my ubuntu and it seemed fine, can you please lete me know if it works for you too?

**Comment by claudiomoratti** [comment]
@kadoshms It works!

I have had to change the include line in app.scss to 
`@import "../../node_modules/ionic2-auto-complete/auto-complete";`
'cause of new structure of sources.

I tested both with @ionic/app-scripts  1.3.7 and 1.3.4, with the same result!

thank you for your work

**Comment by kadoshms** [comment]
@claudiomoratti yeah I forgot to mention that sorry :)

Im closing the issue and will publish this fix soon.

**Comment by MattijsE** [comment]
@1.4.0-fix-to-38 did indeed fix the issue (+ changing the SSCC import)
When can we expect this to be committed into the master?
This branch was for 1.4.0, but the current version is 1.4.3

**Comment by kadoshms** [comment]
I am aware of that, it was an innocent typo.
I am working on a much more stable version with some more features, stay tight :)

**Comment by kadoshms** [comment]
@kamok thanks
